package com.simats.frontend;

import android.content.Intent;
import android.os.Bundle;
import android.util.Log;
import android.widget.ArrayAdapter;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.google.gson.JsonObject;
import com.simats.frontend.databinding.ActivityNewPatientBinding;
import com.simats.frontend.network.ApiClient;
import com.simats.frontend.network.ApiInterface;
import com.simats.frontend.models.DoctorPatient;

import java.util.Random;

import retrofit2.Call;
import retrofit2.Callback;
import retrofit2.Response;

public class NewPatientActivity extends AppCompatActivity {

    private ActivityNewPatientBinding binding;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        binding = ActivityNewPatientBinding.inflate(getLayoutInflater());
        setContentView(binding.getRoot());

        // Back button
        binding.btnBack.setOnClickListener(v -> finish());

        // PID will be generated by the backend
        binding.tvPatientId.setText("Auto-generated");

        // Setup Sex Dropdown
        String[] genders = new String[]{"Male", "Female", "Other"};
        ArrayAdapter<String> genderAdapter = new ArrayAdapter<>(this, android.R.layout.simple_dropdown_item_1line, genders);
        binding.tvSexDropdown.setAdapter(genderAdapter);

        // Setup Dept Dropdown
        String[] depts = new String[]{
            "Oral Surgery", "Oral Medicine", "Orthodontics", "Periodontics",
            "Prosthodontics", "Pediatric Dentistry", "Endodontics", "General Dentistry"
        };
        ArrayAdapter<String> deptAdapter = new ArrayAdapter<>(this, android.R.layout.simple_dropdown_item_1line, depts);
        binding.tvDeptDropdown.setAdapter(deptAdapter);

        binding.btnRegister.setOnClickListener(v -> registerPatient());
    }

    private void registerPatient() {
        String generatedId = binding.tvPatientId.getText().toString().trim();
        String fullName = binding.etFullName.getText().toString().trim();
        String mobile = binding.etMobileNumber.getText().toString().trim();
        String ageStr = binding.etAge.getText().toString().trim();
        String gender = binding.tvSexDropdown.getText().toString().trim();
        String department = binding.tvDeptDropdown.getText().toString().trim();
        String email = binding.etEmail.getText().toString().trim();

        if (fullName.isEmpty() || mobile.isEmpty() || ageStr.isEmpty() || gender.isEmpty() || department.isEmpty()) {
            Toast.makeText(this, "Please fill all required fields", Toast.LENGTH_SHORT).show();
            return;
        }

        if (mobile.length() < 10) {
            Toast.makeText(this, "Please enter a valid 10-digit mobile number", Toast.LENGTH_SHORT).show();
            return;
        }

        int age;
        try {
            age = Integer.parseInt(ageStr);
        } catch (NumberFormatException e) {
            Toast.makeText(this, "Please enter a valid age", Toast.LENGTH_SHORT).show();
            return;
        }
        String finalEmail = email.isEmpty() ? null : email;

        ApiInterface apiInterface = ApiClient.getClient(this).create(ApiInterface.class);

        JsonObject requestBody = new JsonObject();
        requestBody.addProperty("name", fullName);
        if (finalEmail != null) {
            requestBody.addProperty("email", finalEmail);
        } else {
            // For patients without email, we still need a unique identifier if the backend requires it for 'users' table,
            // but our new backend logic skips 'users' table if email is null.
            // However, the registerUser API might still hit the /api/auth/register endpoint.
            // Let's check if we should even call registerUser or a dedicated addPatient API.
            requestBody.add("email", com.google.gson.JsonNull.INSTANCE);
        }
        requestBody.addProperty("password", "password123"); // Default for new patients
        requestBody.addProperty("role", "patient");
        requestBody.addProperty("age", age);
        requestBody.addProperty("gender", gender);
        requestBody.addProperty("phone", mobile);
        requestBody.addProperty("department", department);

        binding.btnRegister.setEnabled(false);
        binding.btnRegister.setText("Registering...");

        Call<JsonObject> call = apiInterface.registerUser(requestBody);
        call.enqueue(new Callback<JsonObject>() {
                @Override
                public void onResponse(Call<JsonObject> call, Response<JsonObject> response) {
                    binding.btnRegister.setEnabled(true);
                    binding.btnRegister.setText("Register Patient");

                    if (response.isSuccessful() && response.body() != null) {
                        JsonObject body = response.body();
                        String realPid = body.has("pid") ? body.get("pid").getAsString() : "PID-TBD";
                        
                        Toast.makeText(NewPatientActivity.this, "Patient Registered Successfully!", Toast.LENGTH_LONG).show();
                        
                        Intent intent = new Intent(NewPatientActivity.this, PatientRegistrationCompleteActivity.class);
                        intent.putExtra("PATIENT_NAME", fullName);
                        intent.putExtra("PATIENT_ID", realPid);
                        intent.putExtra("PATIENT_MOBILE", mobile);
                        startActivity(intent);
                        
                        finish(); 
                    } else {
                    String errorMsg = "Registration failed";
                    try {
                        if (response.errorBody() != null) {
                            com.google.gson.JsonObject errObj = com.google.gson.JsonParser.parseString(response.errorBody().string()).getAsJsonObject();
                            if (errObj.has("message")) errorMsg = errObj.get("message").getAsString();
                        }
                    } catch (Exception e) { e.printStackTrace(); }
                    android.util.Log.e("NewPatientActivity", "Registration error " + response.code() + ": " + errorMsg);
                    Toast.makeText(NewPatientActivity.this, errorMsg, Toast.LENGTH_LONG).show();
                }
            }

            @Override
            public void onFailure(Call<JsonObject> call, Throwable t) {
                binding.btnRegister.setEnabled(true);
                binding.btnRegister.setText("Register Patient");
                Toast.makeText(NewPatientActivity.this, "Network error: " + t.getMessage(), Toast.LENGTH_SHORT).show();
            }
        });
    }
}
